import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-providex";
import { ModeToggle } from "./utils/dark-theme/toggle-dark";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableColorScheme
        >
          <div className="flex justify-end p-4">
            <ModeToggle></ModeToggle>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
